DELETE http://localhost:3003/api/blogs/60a38e7d7636682184fa1856
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVra28iLCJpZCI6IjYwYTE3NDExM2VhZjFkNTU0MGUyNTMyYiIsImlhdCI6MTYyMTMyOTgwMSwiZXhwIjoxNjIxMzMzNDAxfQ.Bql7ulSvoKSf8BIfPWtgB47Y4C03QadEqkoQld_xqlw